# Generated by Django 4.1.2 on 2022-10-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='static/media/About'),
        ),
        migrations.AlterField(
            model_name='about',
            name='large_image',
            field=models.ImageField(upload_to='static/media/About'),
        ),
    ]
