# Generated by Django 4.1.2 on 2022-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='blogs.category'),
        ),
    ]
