# Generated by Django 4.1.2 on 2022-10-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_bloglist_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='image',
            field=models.ImageField(upload_to='static/media/images/'),
        ),
    ]
